slugable behavior - scope column overrides $getter
If scope is enabled the `$getter` variable was overriden by scope column, which causes
```
Fatal error: Unsupported operand types
```