Fixed serializer for datetime primary keys
If you have a datetime type in a primary key, when you generate a key for pool you obtained:

ERROR: Catchable Fatal Error: Object of class DateTime could not be converted to string in ... line ...

It's occurs because it tries to convert pk to string before serialize. 